-- SELECT ATTRIBUTES NEEDED BY R SCRIPT
DROP TABLE IF EXISTS :OUTSCHEMA.:ATTRIBS;CREATE TABLE :OUTSCHEMA.:ATTRIBS AS
SELECT nodeid,eco_id_int "ECO_Id_int", 
ROUND(area_geo::numeric,4) "AREA_GEO"
FROM :OUTSCHEMA.:INTABLE
ORDER BY nodeid;

