-- SELECT ATTRIBUTES NEEDED BY R SCRIPT
DROP TABLE IF EXISTS :OUTSCHEMA.:ATTRIBS;CREATE TABLE :OUTSCHEMA.:ATTRIBS AS
SELECT nodeid "OBJECTID",iso3final "ISO3final",
ROUND(area_geo::numeric,4) "AREA_GEO"
FROM :OUTSCHEMA.:INTABLE
ORDER BY objectid;

