# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# a2country.py
# Created on: 2019-10-29 13:46:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: GIS processing for Country-ProtCoon (part 2#2)
# ---------------------------------------------------------------------------

# Import arcpy module
import sys
import arcpy
from arcpy import env
import os
import os.path

from datetime import datetime
firststarttime=datetime.now()

print(" ")
print("PROCEDURE STARTED at ", datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
print('-------------------------------------------------------')

# Working Geodatabase
wdpadate="202302"
outpath="Z:/globes/USERS/GIACOMO/protconn/data/"+wdpadate
# outgdb_name="ProtConn_"+wdpadate+".gdb"
outgdb_name="test_ungeo.gdb"
outgdb_fullpath = outpath+"/"+outgdb_name+"/"

# Set environment variables
arcpy.env.workspace = outgdb_fullpath
arcpy.env.overwriteOutput = True

# input shapefile
input_shp = outpath+"/wdpa_all_relevant_simpl.shp"

# Local variables
wdpa_all_relevant_simpl = "wdpa_all_relevant_simpl"
wdpa_all_relevant_simpl_fullpath = outgdb_fullpath+wdpa_all_relevant_simpl
wdpa_all_relevant_simpl_dissolved_ISO3 = outgdb_fullpath+"wdpa_all_relevant_simpl_dissolved_ISO3"
dissolved_iso3_over_1_km2 = outgdb_fullpath+"dissolved_iso3_over_1_km2"
# gaul_source="Z:/globes/USERS/GIACOMO/protconn/data/BaseLayers.gdb/gaul"
#gaul = outgdb_fullpath+"gaul"
gaul_source="Z:/globes/USERS/GIACOMO/protconn/data/BaseLayers.gdb/ungeo_national"
gaul_fc="ungeo_national"
gaul = outgdb_fullpath+"ungeo_national"
wdpa_all_relevant_simpl_dissolved_iso3_clipped_land = outgdb_fullpath+"wdpa_all_relevant_simpl_dissolved_iso3_clipped_land"
dissolved_iso3_clipped_land_over_1_km2 = outgdb_fullpath+"dissolved_iso3_clipped_land_over_1_km2"
# select_only_multi_iso3 = dissolved_iso3_clipped_land_over_1_km2
# select_NO_multi_iso3 = dissolved_iso3_clipped_land_over_1_km2
wdpa_NO_multi_iso3 = outgdb_fullpath+"wdpa_NO_multi_iso3"
iso3_no_multi = outgdb_fullpath+"iso3_no_multi"
iso3_multi = outgdb_fullpath+"iso3_multi"
iso3_multi_erased = outgdb_fullpath+"iso3_multi_erased"
intersected_gaul_erased = outgdb_fullpath+"intersected_gaul_erased"
wdpa_only_multi_iso3 = outgdb_fullpath+"wdpa_only_multi_iso3"
wdpa_multi_iso3_together = outgdb_fullpath+"wdpa_multi_iso3_together"
wdpa_multi_iso3_together_dissolved_ISO3final = outgdb_fullpath+"wdpa_multi_iso3_together_dissolved_ISO3final"
wdpa_multi_iso3_together_dissolved_ISO3final_LYR = "wdpa_multi_iso3_together_dissolved_ISO3final_LYR"
wdpa_multi_iso3_together_dissolved_ISO3final_1km2 = outgdb_fullpath+"wdpa_multi_iso3_together_dissolved_ISO3final_1km2"
wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted = outgdb_fullpath+"wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted"
wdpa_flat_1km_final = outgdb_fullpath+"wdpa_flat_1km_final_"+wdpadate
# all_distances = "all_distances_wdpa_country_300km" # No more needed
# outfile_dist=outpath+"/"+all_distances+".txt" # No more needed
outfile_attr="attrib_table_wdpa_flat_"+wdpadate+".txt"

# Process: Create GDB 
if arcpy.Exists(outgdb_fullpath):
	print(outgdb_name, " already exists.")
else:
	arcpy.CreateFileGDB_management(outpath, outgdb_name)
	print(outgdb_name, " created")

# Process: copy gaul from BaseLayers.gdb
arcpy.FeatureClassToFeatureClass_conversion(in_features = gaul_source, out_path = outgdb_fullpath, out_name = gaul_fc, where_clause="", config_keyword="")
print("Administrative boundaries imported")

# Process: Feature Class to Feature Class
# arcpy.FeatureClassToFeatureClass_conversion(input_shp, outgdb_fullpath, wdpa_all_relevant_simpl, "", "", "")

# Process: Define Projection
arcpy.DefineProjection_management(wdpa_all_relevant_simpl_fullpath, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
print("Simplified features imported")

# Process: Repair Geometry (2)
arcpy.RepairGeometry_management(wdpa_all_relevant_simpl_fullpath, "DELETE_NULL")
print("Geometries repaired")

# Process: Dissolve
arcpy.Dissolve_management(wdpa_all_relevant_simpl_fullpath, wdpa_all_relevant_simpl_dissolved_ISO3, "iso3", "", "SINGLE_PART", "DISSOLVE_LINES")
print("Features dissolved")

# Process: Repair Geometry
arcpy.RepairGeometry_management(wdpa_all_relevant_simpl_dissolved_ISO3, "DELETE_NULL")
print("Geometries repaired")

# Process: Add Geometry Attributes
arcpy.AddGeometryAttributes_management(wdpa_all_relevant_simpl_dissolved_ISO3, "AREA_GEODESIC", "", "SQUARE_KILOMETERS", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
print("Area_geo computed")


########################
# Process: Make Feature Layer over 1 km2
arcpy.MakeFeatureLayer_management(wdpa_all_relevant_simpl_dissolved_ISO3, "dissolved_iso3_over_1_km2_lyr")
arcpy.SelectLayerByAttribute_management("dissolved_iso3_over_1_km2_lyr","NEW_SELECTION", "\"AREA_GEO\" >=1")
arcpy.CopyFeatures_management("dissolved_iso3_over_1_km2_lyr",dissolved_iso3_over_1_km2)
print("Feature Layer over 1km2 created")

# Process: Clip
arcpy.Clip_analysis(dissolved_iso3_over_1_km2, gaul, wdpa_all_relevant_simpl_dissolved_iso3_clipped_land, "")
print("Features clipped on adm boundaries")

# Process: Add Geometry Attributes (2)
arcpy.AddGeometryAttributes_management(wdpa_all_relevant_simpl_dissolved_iso3_clipped_land, "AREA_GEODESIC", "", "SQUARE_KILOMETERS", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
print("Area_geo re-computed")

# Process: Make Feature Layer over 1 km2 (2)
arcpy.MakeFeatureLayer_management(wdpa_all_relevant_simpl_dissolved_iso3_clipped_land, dissolved_iso3_clipped_land_over_1_km2, "\"AREA_GEO\" >=1", "", "iso3 iso3 VISIBLE NONE;AREA_GEO AREA_GEO VISIBLE NONE;Shape_length Shape_length VISIBLE NONE;Shape_area Shape_area VISIBLE NONE")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(dissolved_iso3_clipped_land_over_1_km2, "NEW_SELECTION", "iso3 NOT LIKE '%;%'")

# Process: Make Feature Layer NO multi iso3
arcpy.MakeFeatureLayer_management(dissolved_iso3_clipped_land_over_1_km2, wdpa_NO_multi_iso3, "", "", "iso3 iso3 VISIBLE NONE;AREA_GEO AREA_GEO VISIBLE NONE;Shape_length Shape_length VISIBLE NONE;Shape_area Shape_area VISIBLE NONE")

# Process: Copy Features NO multi iso3
arcpy.CopyFeatures_management(wdpa_NO_multi_iso3, iso3_no_multi, "", "0", "0", "0")
print("Feature class with only No-multi iso3 created")

# Process: Add Field myISO3
arcpy.AddField_management(iso3_no_multi, "myISO3", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field myISO3
arcpy.CalculateField_management(iso3_no_multi, "myISO3", "!iso3!", "PYTHON", "")
print("Features no-multi iso3 processed")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(dissolved_iso3_clipped_land_over_1_km2, "NEW_SELECTION", "iso3 LIKE '%;%'")

# Process: Make Feature Layer only multi iso3
arcpy.MakeFeatureLayer_management(dissolved_iso3_clipped_land_over_1_km2, wdpa_only_multi_iso3, "", "", "iso3 iso3 VISIBLE NONE;AREA_GEO AREA_GEO VISIBLE NONE;Shape_length Shape_length VISIBLE NONE;Shape_area Shape_area VISIBLE NONE")

# Process: Copy Features
arcpy.CopyFeatures_management(wdpa_only_multi_iso3, iso3_multi, "", "0", "0", "0")
print("Feature class with only multi iso3 created")

# Process: Erase
arcpy.Erase_analysis(iso3_multi, iso3_no_multi, iso3_multi_erased, "")

# Process: Intersect
arcpy.Intersect_analysis([iso3_multi_erased,gaul], intersected_gaul_erased, "ALL", "", "INPUT")
print("Multi iso3 erased and intersected with adm boundaries")

# Process: Add Field myISO3 (2)
arcpy.AddField_management(intersected_gaul_erased, "myISO3", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field myISO3 (2)
arcpy.CalculateField_management(intersected_gaul_erased, "myISO3", "!iso3_1!", "PYTHON", "")

# Process: Merge
arcpy.Merge_management([iso3_no_multi,intersected_gaul_erased], wdpa_multi_iso3_together)
print("Features multi iso3 processed")

# Process: Add Field ISO3final (3)
arcpy.AddField_management(wdpa_multi_iso3_together, "ISO3final", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field myISO3 (3)
arcpy.CalculateField_management(wdpa_multi_iso3_together, "ISO3final", "!myISO3!", "PYTHON", "")

# Process: Dissolve by ISO3final
arcpy.Dissolve_management(wdpa_multi_iso3_together, wdpa_multi_iso3_together_dissolved_ISO3final, "ISO3final", "", "SINGLE_PART", "DISSOLVE_LINES")
print("Features dissolved")

# Process: Add Geometry Attributes (3)
arcpy.AddGeometryAttributes_management(wdpa_multi_iso3_together_dissolved_ISO3final, "AREA_GEODESIC", "", "SQUARE_KILOMETERS", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Make Feature Layer >=1 1km2
arcpy.MakeFeatureLayer_management(wdpa_multi_iso3_together_dissolved_ISO3final, wdpa_multi_iso3_together_dissolved_ISO3final_LYR, "\"AREA_GEO\" >=1", "", "ISO3final ISO3final VISIBLE NONE;AREA_GEO AREA_GEO VISIBLE NONE")
print("Geodesic area computed and features < 1km2 filtered out")

# Process: Copy Features NO multi iso3 (2)
arcpy.CopyFeatures_management(wdpa_multi_iso3_together_dissolved_ISO3final_LYR, wdpa_multi_iso3_together_dissolved_ISO3final_1km2, "", "0", "0", "0")

# Process: Repair Geometry (3)
arcpy.RepairGeometry_management(wdpa_multi_iso3_together_dissolved_ISO3final_1km2, "DELETE_NULL")
print("Geometry of multi-iso3 features repaired")

# Process: Multipart To Singlepart
arcpy.MultipartToSinglepart_management(wdpa_multi_iso3_together_dissolved_ISO3final_1km2, wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted)
print("multi-iso3 converted to single part")

# Process: Add Geometry Attributes (4)
arcpy.AddGeometryAttributes_management(wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted, "AREA_GEODESIC", "", "SQUARE_KILOMETERS", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Repair Geometry (4)
arcpy.RepairGeometry_management(wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted, "DELETE_NULL")
print("Geometries re-repaired for the nth time....")

# Process: Add Field nodeID
arcpy.AddField_management(wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted, "nodeID", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted, "nodeID", "!OBJECTID!", "PYTHON", "")
print("Field nodeID computed")

# Process: Copy Features (2)
arcpy.CopyFeatures_management(wdpa_multi_iso3_together_dissolved_ISO3final_1km2_singleparted, wdpa_flat_1km_final, "", "0", "0", "0")
print("Final layer copied to wdpa_flat_1km_final")

# # Table to table (txt) with field mapping (no more needed, better to do it in postgis)
# arcpy.TableToTable_conversion(in_rows=wdpa_flat_1km_final, out_path=outpath, out_name=outfile_attr)
# print("Attribute Table exported in .txt")

# # Process: Copy Features to shapefile (NO MORE NEEDED: NOW THE LAYER IS IMPORTED IN POSTGIS DIRECTLY FROM GDB)
# arcpy.FeatureClassToFeatureClass_conversion(in_features=wdpa_flat_1km_final, out_path=outpath, out_name=wdpa_flat_1km_final, where_clause="", field_mapping='ISO3final "ISO3final" true true false 50 Text 0 0 ,First,#,wdpa_flat_1km_final,ISO3final,-1,-1;AREA_GEO "AREA_GEO" true true false 8 Double 0 0 ,First,#,wdpa_flat_1km_final,AREA_GEO,-1,-1;ORIG_FID "ORIG_FID" true true false 4 Long 0 0 ,First,#,wdpa_flat_1km_final,ORIG_FID,-1,-1;nodeID "nodeID" true true false 4 Long 0 0 ,First,#,wdpa_flat_1km_final,nodeID,-1,-1;Shape_Leng "Shape_Leng" false true true 8 Double 0 0 ,First,#,wdpa_flat_1km_final,Shape_Length,-1,-1;Shape_Area "Shape_Area" false true true 8 Double 0 0 ,First,#,wdpa_flat_1km_final,Shape_Area,-1,-1', config_keyword="")
# print("wdpa_flat_1km_final exported to Shapefile")

# # Process: Generate Near Table(MUCH BETTER/FASTER IN POSTGIS)
# print("Now generating Near Table. If you want to do it in postgis, kill the script now and execute in docker the script /globes/USERS/GIACOMO/protconn/scripts/exec_near_table_country_parallel.sh")
# arcpy.GenerateNearTable_analysis(wdpa_flat_1km_final, wdpa_flat_1km_final, all_distances, "300 Kilometers", "NO_LOCATION", "NO_ANGLE", "ALL", "0", "GEODESIC")
# print("Near Table generated")

# # Process: Copy Rows
# arcpy.CopyRows_management(all_distances, outfile_dist)
# print("Near Table exported in .txt")

print('-------------------------------------------------------')
endtime=datetime.now()
totaltime= endtime-firststarttime
print(' ')
print('PROCEDURE COMPLETED. Elapsed time: ', totaltime)
print('Now execute in docker the script "/globes/USERS/GIACOMO/protconn/scripts/gis_proc/exec_near_table_country_parallel.sh" ')
print(' ')

# close procedure
sys.exit()
